<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'block_mycourse_recommendations', language 'en'.
 *
 * @package   block_mycourse_recommendations
 * @copyright 2015 onwards Iñaki Arenaza & Mondragon Unibertsitatea
 *            2016 onwards Julen Pardo & Mondragon Unibertsitatea
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'MYCOURSE Recommendations';
$string['crontask'] = 'Recommendations creation job.';
$string['norecommendations'] = 'There are no recommendations for you for this week.';
$string['notpersonalizable'] = 'This course won\'t receive recommendations because it is not personalizable.';
$string['inactive'] = 'This course won\'t receive more recommendations because is inactive.';
$string['usernotselected'] = 'You are not selected to receive recommendations.';
$string['importfromcsv'] = 'Import data from CSV file';
$string['upload'] = 'Upload historic courses data';
$string['upload_title'] = 'MyCourse Recommendations - Import data';
$string['upload_desc'] = "This is the form to upload historic information, that will be associated directly to this course.
Please note that csv must be uploaded with NO HEADERS.<hr>";
$string['uploaddata'] = 'Upload data';

$string['coursefile'] = 'CSV with course information';
$string['coursefile_desc'] = "Attach here the csv with the information of the course. Please remember that, in this version, the
courses must be uploaded one by one, so only the first data row in the csv will be imported.
<br>The format must be the following: | fullname | shortname | startdate | idnumber | category |";

$string['usersfile'] = 'CSV with users\' enrolments in courses';
$string['usersfile_desc'] = "Attach here the csv with the information of the users enrolled in the course attached on the previous
field.
<br>The format must be the following: | userid | grade |";

$string['logsfile'] = 'CSV with log information';
$string['logsfile_desc'] = "Attach here the csv with the information of the log views generated by the users for the resources.
<br>The format must be the following: | userid | resourcename | resourcetype | resourceid | views | timecreated |";

$string['success'] = 'The importation was made successfully';
$string['importedcourses'] = 'Imported courses: ';
$string['importedusers'] = 'Imported users: ';
$string['importedlogs'] = 'Imported logs: ';
$string['errorimporting'] = "An error occurred while importing the data:<br>";
